### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by mtfbw-honami36** [mtfbw-honami36/furima-28825#12]
#本番環境URL
https://furima-28825.herokuapp.com/
#Basic認証
　ID：furima28825
　PASSWORD：9536
#出品者
　MAIL：hoge@sample.com
　PASSWORD：check36
#購入者
　MAIL：fuga@sample.com
　PASSWORD：check36
#カード情報
　番号：4242424242424242
　期限：12/24
　コード：123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
